### ISSUE TITLE
vue-plugin as local dependency

### ISSUE THREAD

**Issue by Hatead1** [retejs/vue-render-plugin#77]
Сreate test vue2 app with rete-kit - everything is fine, compiles and works.

But

Clone vue-plugin (install/build), add plugin as local dep ("rete-vue-plugin": "file:../vue-plugin/dist"), install/run - tonns of compile error like

108 > |  area.use(vueRender);
        |            ^^^^^^^^^
    109 |   area.use(connection);
    110 |   area.use(contextMenu);
    111 |

 error  in src/rete/perf.ts:38:12

TS2345: Argument of type 'VuePlugin<Schemes, AreaExtra>' is not assignable to parameter of type 'Scope<any, any[]>'.
  The types of 'use(...).debug' are incompatible between these types.
    Type '<T extends FilterNever<GetAllNonValidElements<UnionToTuple<S["__scope"]["parents"][number]>, AreaExtra | Produces<Schemes> | Requires<Schemes>>>>(f: (p: { [K in keyof T]: AreaExtra | ... 1 m
ore ... | Requires<...>; }) => T) => void' is not assignable to type '<T extends FilterNever<GetAllN
onValidElements<UnionToTuple<S["__scope"]["parents"][number]>, any>>>(f: (p: { [K in keyof T]: any;
}) => T) => void'.
      Types of parameters 'f' and 'f' are incompatible.
...

**Comment by Ni55aN** [comment]
It is recommended to use [`rete-kit build`](https://retejs.org/docs/development/rete-kit#build-deps-rete-kit) since npm link (or `file:../`)  has limitations and isn't suitable for cases where dependencies require the same copy of their common dependency. At least, you can run `npm link` for common dependencies (../vue-plugin/dist` should refer to `rete` package of your application that has ../vue-plugin installed), but it still isn't reliable way.

It is recommended to use the rete-kit build, as the npm link (or file:../) has limitations and is not suitable for cases where dependencies must share the same copy of their shared dependency. At the very least, you can run an npm link for shared dependencies (../vue-plugin/dist should link to the torete` package in your app's node_modules, where the link is to ../vue-plugin, but this is still not DX-friendly approach

**Comment by Ni55aN** [comment]
It is recommended to use [`rete-kit build`](https://retejs.org/docs/development/rete-kit#build-deps-rete-kit) since npm link (or `file:../`)  has limitations and isn't suitable for cases where dependencies require the same copy of their common dependency. At least, you can run `npm link` for common dependencies (../vue-plugin/dist` should refer to `rete` package of your application that has ../vue-plugin installed), but this is still not DX-friendly approach
